---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry/"
webhook_url: 
sections:
- type: directory
  path: src
  label: src pages
  create: all
  match: "**/*"
- type: heading
  label: adsfasdf
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
